package spark.sample;

import static spark.Spark.get;

import java.time.LocalDateTime;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class SparkApplication {
	private static Timer timer = new Timer();
	
    public static void main(String[] args) {
    	get("/", (req, res) -> {
    		timer.countUp();
    		
    		return "Spark";
    	});
    }
    
    static class Timer{
    	private int counter = 0;
    	public void countUp() {
    		counter++;
    		if(counter == 1) {
        		System.out.println(LocalDateTime.now());
        	}
        	
        	if(counter == 10000) {
        		System.out.println(LocalDateTime.now());
        	}
    	}
    }
}
